-- Create public calculations table
CREATE TABLE IF NOT EXISTS calculations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  examiner_id TEXT NOT NULL,
  date TIMESTAMP WITH TIME ZONE DEFAULT now(),
  papers INTEGER NOT NULL,
  rate DECIMAL(10, 2) NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  user_id UUID REFERENCES auth.users(id),
  pdf_path TEXT
);

-- Create a row-level security policy
ALTER TABLE calculations ENABLE ROW LEVEL SECURITY;

-- Policies for authenticated users
CREATE POLICY "Allow users to read own calculations" ON calculations
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert own calculations" ON calculations
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update own calculations" ON calculations
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete own calculations" ON calculations
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id); 