-- Create public examiners table
CREATE TABLE IF NOT EXISTS examiners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  examiner_id TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  department TEXT,
  phone TEXT,
  email TEXT,
  profile_pic TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  user_id UUID REFERENCES auth.users(id)
);

-- Create a row-level security policy
ALTER TABLE examiners ENABLE ROW LEVEL SECURITY;

-- Policies for authenticated users
CREATE POLICY "Allow users to read own examiners" ON examiners
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert own examiners" ON examiners
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update own examiners" ON examiners
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete own examiners" ON examiners
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id); 