-- Create public settings table
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  value JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create a row-level security policy
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Policies for authenticated users
CREATE POLICY "Allow full access to authenticated users" ON settings
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Insert default settings if they don't exist
INSERT INTO settings (key, value) 
VALUES ('theme', '{"isDarkMode": false}')
ON CONFLICT (key) DO NOTHING;

INSERT INTO settings (key, value) 
VALUES ('pdfSaveLocation', '"./downloads"')
ON CONFLICT (key) DO NOTHING;

INSERT INTO settings (key, value) 
VALUES ('evaluationRate', '20.0')
ON CONFLICT (key) DO NOTHING; 